#ifndef STATIC_CONFIG_H
#define STATIC_CONFIG_H

#define MAX_HEADER_KEY_SIZE 64
#define MAX_HEADER_VALUE_SIZE 256

#define MAX_REQUEST_TYPE_SIZE 8
#define MAX_REQUEST_PATH_SIZE 64
#define MAX_REQUEST_HEADERS 16

#define MAX_RESPONSE_STATUS_MESSAGE_SIZE 32
#define MAX_RESPONSE_HEADERS 16
#define MAX_RESPONSE_BODY_SIZE 4096

#endif
